name: Auto Merge Dev into Main

on:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Auto merge dev into main
      uses: 
      with:
        args: branch main
      run:
        git config --global user.email "katyayana2003@gmail.com"
        git config --global user.name "vedant-204"
        git checkout main
        git merge dev
        git push origin main
